name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Configure Poetry
        run: python -m poetry config virtualenvs.in-project true
      
      - name: Set up Make
        run: sudo apt-get update && sudo apt-get install make
      
      - name: Run static analysis
        run: make check
      
      - name: Run unit tests
        run: make test-unit
