name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Make
        run: sudo apt-get update && sudo apt-get install make
      
      - name: Run static analysis
        run: make check
      
      - name: Run unit tests
        run: make test-unit
